Test the myconf CLI

  $ myconf fmt file simple.myconf
  name = "my-app"
  port = 8080
  debug = true

Test with comments:

  $ myconf fmt file comments.myconf
  # This is a config file
  # With multiple comments
  name = "test"
  value = 123

Test dump command:

  $ myconf fmt dump simple.myconf
  ((Binding ((loc _) (key name) (value (String my-app))))
   (Binding ((loc _) (key port) (value (Int 8080))))
   (Binding ((loc _) (key debug) (value (Bool true)))))

Test dump with locations:

  $ myconf fmt dump --loc simple.myconf
  ((Binding
    ((loc ((start simple.myconf:1:0) (stop simple.myconf:1:15))) (key name)
     (value (String my-app))))
   (Binding
    ((loc ((start simple.myconf:2:0) (stop simple.myconf:2:11))) (key port)
     (value (Int 8080))))
   (Binding
    ((loc ((start simple.myconf:3:0) (stop simple.myconf:3:12))) (key debug)
     (value (Bool true)))))

Test formatting with dynamically created file:

  $ cat > dynamic.myconf << 'EOF'
  > message="hello world"
  > count=42
  > enabled=true
  > EOF

  $ myconf fmt file dynamic.myconf
  message = "hello world"
  count = 42
  enabled = true

Test gen-dune command:

  $ myconf fmt gen-dune '%{bin:myconf}' fmt file
  ; dune file generated by '%{bin:myconf} fmt gen-dune' -- do not edit.
  (rule
   (with-stdout-to comments.myconf.pp.output
    (run %{bin:myconf} fmt file %{dep:comments.myconf})))
  (rule (alias fmt) (action (diff comments.myconf comments.myconf.pp.output)))
  (rule
   (with-stdout-to dynamic.myconf.pp.output
    (run %{bin:myconf} fmt file %{dep:dynamic.myconf})))
  (rule (alias fmt) (action (diff dynamic.myconf dynamic.myconf.pp.output)))
  (rule
   (with-stdout-to simple.myconf.pp.output
    (run %{bin:myconf} fmt file %{dep:simple.myconf})))
  (rule (alias fmt) (action (diff simple.myconf simple.myconf.pp.output)))

Test error handling with invalid syntax:

  $ cat > invalid.myconf << 'EOF'
  > this is not valid
  > EOF

  $ myconf fmt file invalid.myconf
  File "invalid.myconf", line 1, characters 5-7:
  1 | this is not valid
           ^^
  Error:  syntax error.
  [123]

Test sorting with MYCONF_SORT_ENTRIES - creates unsorted file:

  $ cat > unsorted.myconf << 'EOF'
  > zebra = "last"
  > alpha = "first"
  > middle = 42
  > EOF

Without sorting, order is preserved:

  $ myconf fmt file unsorted.myconf
  zebra = "last"
  alpha = "first"
  middle = 42

With MYCONF_SORT_ENTRIES=true, entries are sorted but AST change is detected:

  $ MYCONF_SORT_ENTRIES=true myconf fmt file unsorted.myconf
  Error: AST changed during pretty-printing.
  alpha = "first"
  middle = 42
  zebra = "last"
  [123]

With AUTO_FORMAT_ALLOW_CHANGES=true, the AST change is permitted:

  $ MYCONF_SORT_ENTRIES=true AUTO_FORMAT_ALLOW_CHANGES=true myconf fmt file unsorted.myconf
  alpha = "first"
  middle = 42
  zebra = "last"
